import type { Metadata } from "next";
import "./globals.css";



export const metadata: Metadata = {
  title: "Dragon Ball characters",
  description: "Generated by dinz kramer",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
